pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "spring-boot/spring-boot-image:${BUILD_NUMBER}"
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
    }

    stages {
        
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/Heena-dotcom/Spring-boot-jenkins-argocd.git'
            }
        }
        
        stage('Build and Test') {
            steps {
                sh 'ls -ltr'
                sh 'cd spring-boot-app && mvn clean package'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }
        
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for more details.'
        }
    }
}